name: cargo-sweep
author: BD103
description: Sweep away unused Cargo files from the `target` directory.
inputs:
  project-path:
    description: |
      The path to the folder containing `Cargo.toml` and `target`, without a trailing slash. By
      default this is the current working directory.
    required: false
    default: '.'
runs:
  using: node20
  main: dist/main/index.js
  post: dist/post/index.js
branding:
  icon: trash-2
  color: orange
