name: cargo-sweep
author: BD103
description: Sweep away unused Cargo files from the `target` directory.
inputs:
  manifest-path:
    description: |
      The path to `Cargo.toml`, used to discover the Cargo workspace and `target` directory. By
      default this is the `Cargo.toml` in the current working directory.
    required: true
    default: Cargo.toml
runs:
  using: node20
  main: dist/main/index.js
  post: dist/post/index.js
branding:
  icon: trash-2
  color: orange
