name: cargo-sweep
author: BD103
description: Sweep away unused Cargo files from the `target` directory.
inputs:
  gh-token:
    description: |
      The Github token used to fetch the most recent artifact. This defaults to
      `github.token`, but is only required if `use-prebuilt` is true.
    required: false
    default: ${{ github.token }}
  use-prebuilt:
    description: |
      If true, the action will download a prebuilt binary of `cargo-sweep` instead of installing it
      using `cargo install`. By default this is false.
    required: false
    default: false
runs:
  using: node20
  main: dist/main/index.js
  post: dist/post/index.js
branding:
  icon: trash-2
  color: orange
