name: Test action

on:
  # Runs when someone pushes to the main branch.
  push:
    branches: [main]
  # Runs when someone updates a PR.
  pull_request:
  # Allow running manually.
  workflow_dispatch:

jobs:
  test:
    name: 'Test action (${{ matrix.os }})'
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        # project-path: ['.', subdir]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Initialize Rust project
        run: cargo init --bin

      - name: Cache build files
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-${{ hashFiles('**/Cargo.toml') }}
          path: target

      - name: Build Rust project
        # working-directory: ${{ matrix.project-path }}
        run: cargo build

      - name: cargo-sweep
        uses: ./
        # with:
        #   project-path: ${{ matrix.project-path }}

      - name: Check Rust project
        # working-directory: ${{ matrix.project-path }}
        run: cargo check

      # `cargo-sweep` should delete all build files, but keep the check ones.
